language: python
python:
  - "2.6"
  - "2.7"

install:
  - pip install --editable .
  - pip install -r requirements_dev.txt
  - pip install coveralls

script:
  - nosetests --with-coverage --cover-package=ubackup

after_success:
  coveralls
