language: python
python:
  - "2.6"
  - "2.7"

install:
  - pip install --editable .
  - pip install -r requirements_dev.txt
  - pip install coveralls

script:
  - make test

after_success:
  coveralls

notifications:
  email:
    recipients:
      - thomas.kliszowski@gmail.com
    on_success: change
    on_failure: always
